# Generated by Django 5.2.4 on 2025-07-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='프로필 사진'),
        ),
    ]
